---
name: CI

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 17 ]
    name: Java ${{ matrix.java }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Azul JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Test with Maven
        run: mvn test --no-transfer-progress